version: 2.1
jobs:
  terraform_plan:
    docker:
    - image: hashicorp/terraform:light
    steps:
    - checkout
    - run:
        name: Initialize Terraform
        working_directory: ~/project/remote-state
        command: terraform init
    - run:
        name: Terraform Plan
        working_directory: ~/project/remote-state
        command: terraform plan

  terraform_apply:
    working_directory: ~/project/remote-state/
    docker:
    - image: hashicorp/terraform:light
    steps:
    - checkout
    - run:
        name: Initialize Terraform
        working_directory: ~/project/remote-state
        command: terraform init
    - run:
        name: Terraform Apply
        working_directory: ~/project/remote-state
        command: terraform apply -auto-approve

workflows:
  version: 2
  build_and_deploy:
    jobs:
    - terraform_plan
    - terraform_apply:
        requires:
        - terraform_plan
