


jobs:
  determine-changes:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run: |
          if git diff --name-only origin/main HEAD | grep '^app/'; then
            echo "Detected app changes - triggering Docker build"
            echo '{"build_docker": true, "run_terraform": false}' > continuation-config.json
          elif git diff --name-only origin/main HEAD | grep '^infra/'; then
            echo "Detected infra changes - triggering Terraform"
            echo '{"build_docker": false, "run_terraform": true}' > continuation-config.json
          fi


# Mit continuation-config.json
version: 2.1

executors:
  default:
    docker:
      - image: cimg/base:current

jobs:
  determine-changes:
    executor: default
    steps:
      - checkout
      - run: |
          if git diff --name-only origin/main | grep -q '^app/'; then
            echo "BUILD_DOCKER=true" >> pipeline-flags.env
          else
            echo "BUILD_DOCKER=false" >> pipeline-flags.env
          fi

          if git diff --name-only origin/main | grep -q '^infra/'; then
            echo "RUN_TERRAFORM=true" >> pipeline-flags.env
          else
            echo "RUN_TERRAFORM=false" >> pipeline-flags.env
          fi
      - persist_to_workspace:
          root: .
          paths:
            - pipeline-flags.env

  docker-build:
    executor: default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: |
          source pipeline-flags.env
          if [ "$BUILD_DOCKER" != "true" ]; then
            echo "No Docker changes detected. Skipping Docker build."
            exit 0
          fi
          echo "Building Docker image..."
          docker build -t myapp:latest .
          docker push myapp:latest

  terraform-apply:
    executor: default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: |
          source pipeline-flags.env
          if [ "$RUN_TERRAFORM" != "true" ]; then
            echo "No Terraform changes detected. Skipping Terraform."
            exit 0
          fi
          echo "Running Terraform apply..."
          cd infra
          terraform init
          terraform apply -auto-approve

workflows:
  version: 2
  ci-workflow:
    jobs:
      - determine-changes
      - docker-build:
          requires:
            - determine-changes
      - terraform-apply:
          requires:
            - determine-changes